version: '3.3'

services:
  app:
    build: .
    ports:
      - 25000:25000
    depends_on:
      - db
    environment:
      - DB_USER=db_user
      - DB_PASSWORD=db_password
      - DB_NAME=db_name
      - DB_HOST=db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
    ports:
      - 5436:5432
