version: '3.3'

services:
  app:
    image: :-
    ports:
      - 25000:25000
    depends_on:
      - db
    environment:
      - DB_USER=test
      - DB_PASSWORD=
      - DB_NAME=
      - DB_HOST=db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=

